
CONFIG_SHELL=n
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
# 0 = OFF, 1 = ERROR, 2 = WARNING, 3 = INFO, 4 = DEBUG
CONFIG_LOG_DEFAULT_LEVEL=0 
CONFIG_LOG_MODE_DEFERRED=y

CONFIG_GPIO=y

CONFIG_STATIC_INIT_GNU=y

CONFIG_I2C=y

CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_LED=y

# Stops from printing *** Booting nRF Connect SDK v3.1.1-e2a97fe2578a ***
CONFIG_NCS_BOOT_BANNER=n
CONFIG_BOOT_BANNER=n
