/*
* File: BLE.cpp
* Author: Daniel Bishara
* Date: March 1, 2026
* Description: define class methods for the BLE class
*/

#include <zephyr/logging/log.h>
#include <zephyr/bluetooth/bluetooth.h>
#include <zephyr/bluetooth/hci.h>
#include <zephyr/bluetooth/gatt.h>
#include <zephyr/bluetooth/uuid.h>
#include <zephyr/bluetooth/conn.h>

#include "BLE.h"

#define DEVICE_NAME CONFIG_BT_DEVICE_NAME
#define DEVICE_NAME_LEN (sizeof(DEVICE_NAME) - 1)

LOG_MODULE_REGISTER( BLEManager, CONFIG_LOG_DEFAULT_LEVEL );

// Don't understand, mostl generated by gemini
static const struct bt_data ad[] = {
    /* 1. Set Flags: General Discoverable + No BREDR (standard for BLE) */
    BT_DATA_BYTES(BT_DATA_FLAGS, (BT_LE_AD_GENERAL | BT_LE_AD_NO_BREDR)),
    
    /* 2. Advertise your custom Accelerometer Service UUID */
    BT_DATA_BYTES(BT_DATA_UUID128_ALL, 
                  0x88, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11,
                  0xFF, 0xEE, 0xDD, 0xCC, 0xAB, 0xAA, 0x00, 0x00),
};

static struct bt_le_adv_param adv_param = BT_LE_ADV_PARAM_INIT(
    BT_LE_ADV_OPT_CONN | BT_LE_ADV_OPT_USE_NAME,
    BT_GAP_ADV_FAST_INT_MIN_2,
    BT_GAP_ADV_FAST_INT_MAX_2,
    NULL
);

// /* Set Scan Response data */
static const struct bt_data sd[] = {
	BT_DATA(BT_DATA_NAME_COMPLETE, DEVICE_NAME, DEVICE_NAME_LEN),
};

/*
 * Custom service/characteristic for accelerometer data.
 * UUIDs generated arbitrarily for example purposes.
 */
static struct bt_uuid_128 accel_service_uuid = BT_UUID_INIT_128(
	0x00, 0x00, 0xAA, 0xAB, 0xCC, 0xDD, 0xEE, 0xFF,
	0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88
);

static struct bt_uuid_128 accel_char_uuid = BT_UUID_INIT_128(
	0x00, 0x00, 0xAA, 0xAC, 0xCC, 0xDD, 0xEE, 0xFF,
	0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88
);

/* storage for the most recent accelerometer reading */
struct AccelData {
	float x;
	float y;
	float z;
};
static uint32_t test_data = 0xDEADBEEF;
static struct AccelData accel_data = {0.0f, 0.0f, 0.0f};
static bool accel_notify_enabled;

static ssize_t read_accel(struct bt_conn *conn,
                          const struct bt_gatt_attr *attr,
                          void *buf, uint16_t len,
                          uint16_t offset)
{
	// const struct AccelData *data = (const struct AccelData *)attr->user_data;
    const uint32_t *data = (const uint32_t *)attr->user_data;
    LOG_INF( "Read request for accelerometer data" );
	return bt_gatt_attr_read(conn, attr, buf, len, offset, data,
	                         sizeof(*data));
}

static void accel_ccc_cfg_changed(const struct bt_gatt_attr *attr,
                                  uint16_t value)
{
	accel_notify_enabled = (value == BT_GATT_CCC_NOTIFY);
}

BT_GATT_SERVICE_DEFINE( accel_svc,
	BT_GATT_PRIMARY_SERVICE(&accel_service_uuid),
	BT_GATT_CHARACTERISTIC(&accel_char_uuid.uuid,
	                       BT_GATT_CHRC_READ | BT_GATT_CHRC_NOTIFY,
	                       BT_GATT_PERM_READ,
	                       read_accel, NULL, &test_data),
	BT_GATT_CCC(accel_ccc_cfg_changed,
	            BT_GATT_PERM_READ | BT_GATT_PERM_WRITE),
    );

static void connected(struct bt_conn *conn, uint8_t err) {
    if (err) {
        LOG_ERR("Connection failed (err %u)", err);
    } else {
        LOG_INF("Connected!");
    }
}

static void disconnected(struct bt_conn *conn, uint8_t reason) {
    LOG_INF("Disconnected (reason %u)", reason);
}

BT_CONN_CB_DEFINE(conn_callbacks) = {
    .connected = connected,
    .disconnected = disconnected,
};

void bt_ready(int err)
{
	char addr_s[BT_ADDR_LE_STR_LEN];
	bt_addr_le_t addr = {0};
	size_t count = 1;

	if (err) {
		LOG_ERR("Bluetooth init failed (err %d)\n", err);
		return;
	}

	LOG_INF("Bluetooth initialized\n");

	/* Start advertising */
	err = bt_le_adv_start(&adv_param, NULL, 0,
			      NULL, 0);
	if (err) {
		LOG_ERR("Advertising failed to start (err %d)\n", err);
		return;
	}


	/* For connectable advertising you would use
	 * bt_le_oob_get_local().  For non-connectable non-identity
	 * advertising an non-resolvable private address is used;
	 * there is no API to retrieve that.
	 */

	bt_id_get(&addr, &count);
	bt_addr_le_to_str(&addr, addr_s, sizeof(addr_s));

	LOG_INF("Beacon started, advertising as %s\n", addr_s);
}

ErrCode_t BLEManager::init( void )
{
    ErrCode_t errCode = ErrCode_Internal;
    int zephyrCode = -ENOTSUP;

    zephyrCode = bt_enable(bt_ready);
    if( zephyrCode )
    {
        LOG_ERR( "Bluetooth init failed (err %d)", zephyrCode );
        goto exit;
    }

    errCode = ErrCode_Success;
exit:
    return errCode;
}