CONFIG_I2C=y
CONFIG_SENSOR=y

CONFIG_LSM6DSO=y
CONFIG_LSM6DSO_TRIGGER_GLOBAL_THREAD=y

# the MAX30101 can be configured on init using various configs, and not through the device tree
CONFIG_MAX30101=y

# CONFIG_NPM1300_CHARGER=n #depends on having dt setup with charger