CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Forge"

CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=n
CONFIG_CLOCK_CONTROL=y
CONFIG_CLOCK_CONTROL_NRF=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_500PPM=y

# Increase the number of buffers available to the controller
CONFIG_BT_BUF_EVT_RX_COUNT=12
CONFIG_BT_BUF_ACL_TX_COUNT=10

CONFIG_BT_CTLR_RX_BUFFERS=15

# Increase the number of advertising sets (nRF54L supports multiple)
CONFIG_BT_EXT_ADV=y
CONFIG_BT_EXT_ADV_MAX_ADV_SET=2

# Essential for nRF54L to prevent memory fragmentation in the controller
CONFIG_BT_CTLR_SDC_MAX_CONN_EVENT_LEN_DEFAULT=0

CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_L2CAP_TX_MTU=247

CONFIG_BT_MAX_CONN=2