CONFIG_I2C=y
CONFIG_SENSOR=y

CONFIG_LSM6DSO=y
CONFIG_LSM6DSO_TRIGGER_GLOBAL_THREAD=y

# the MAX30101 can be configured on init using various configs, and not through the device tree
CONFIG_MAX30101=y
# There is a whole lot of configuration options for the MAX30101, but for now we'll just set it up in heart rate mode with a medium LED power level. 
# See the driver documentation for more details on the various options.
# TODO: we may want to expose some of these options through the device tree or Kconfig in the future, but for now we'll just hardcode them in the driver.
CONFIG_MAX30101_HEART_RATE_MODE=y
CONFIG_MAX30101_SPO2_MODE=n
# With out current PA led current is 6.2mA, less than the max of 8mA, but we may want to increase this in the future if we find that the signal is too weak.
CONFIG_MAX30101_LED1_PA=0xFF
# CONFIG_MAX30101_LED1_PA=0x24 this is better but we set it to 0x02 for debugging
CONFIG_MAX30101_FIFO_A_FULL=0
# 100 samples per second
CONFIG_MAX30101_SR=1 
#average 4 samples
CONFIG_MAX30101_SMP_AVE=4

# Seems resolution is set by LED_PW, default is 18 bits. The driver currently doesn't support changing this, but if we wanted to we could add support for it and then set it here.
# With ADC_RGE set to 0x2, 1 LSB for 18 bits is 31.25 pA, which gives us a max current of about 8 mA
CONFIG_MAX30101_ADC_RGE=1

# CONFIG_NPM1300_CHARGER=n #depends on having dt setup with charger