name: Build nRF54L15 Firmware

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:v2.9-branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: app

      - name: Initialize West
        run: |
          west init -l app
          west update
          west zephyr-export

      - name: Build
        run: |
          west build -b rev1/nrf54l15/cpuapp app \
            --build-dir build_forge \
            -- -DBOARD_ROOT=${{ github.workspace }}/app \
               -DEXTRA_CONF_FILE="configs/sensor.conf;configs/ble.conf"

